language: php
php:
  - 7.0
before_script:
  - composer install
script:
  - php ./vendor/bin/phpcs --standard=psr2 --ignore=vendor -n .
  - php ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
  - ./vendor/bin/test-reporter